version: '2'

services:

    php:
        environment:
            - SYMFONY_ENV=dev
        image: "php"
        build: docker/php
        links:
            - mysql
        env_file:
            - .env
        volumes:
            - ./:/var/www/symfony/

    nginx:
        environment:
            - SYMFONY_ENV=dev
        image: "ngnix:latest"
        build: docker/nginx
        env_file:
            - .env
        ports:
            - 81:80
        links:
            - php
            - mysql
        volumes:
            - ./:/var/www/symfony/

    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=docker
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        container_name: mysql1

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

    maildev:
        image: djfarrelly/maildev
        ports:
            - 8081:80

    blackfire:
        image: blackfire/blackfire
        environment:
            # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
        links:
          - nginx
volumes:
    db_data:
