version: '2'

services:

    php:
        environment:
            - SYMFONY_ENV=dev
        image: "php"
        build: docker/php
        links:
            - mysql
        env_file:
            - .env
        volumes:
            - ./:/var/www/symfony/

    nginx:
        environment:
            - SYMFONY_ENV=dev
        image: "ngnix:latest"
        build: docker/nginx
        env_file:
            - .env
        ports:
            - 81:80
        links:
            - php
            - mysql
        volumes:
            - ./:/var/www/symfony/

    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=docker
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        container_name: mysql1

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

    maildev:
        image: djfarrelly/maildev
        ports:
            - 8081:80

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_CLIENT_ID=540e6ea8-6f7c-49e2-96a8-2559fa82d705
            - BLACKFIRE_CLIENT_TOKEN=87483a5ae1d407ec22aadedd71ea65b2828272e329ea27f9c5a665f0f9fc0d01
            - BLACKFIRE_SERVER_ID=32ac1779-78ae-4f8e-b8bc-b2ca1cc45fa4
            - BLACKFIRE_SERVER_TOKEN=535ee536abf6a10851dad9f197841c1971991a92202a64f1ffdef67816eddf0e
        links:
          - nginx
volumes:
    db_data:
